CXX=g++ -m64
CXXFLAGS+= -Wall -Wshadow -Wstrict-aliasing -ansi -Woverloaded-virtual -Wdelete-non-virtual-dtor
CXXFLAGS+= -pedantic -Weffc++ -Wextra
CXXFLAGS+= -std=c++14 
#-fprefetch-loop-arrays
#CXXFLAGS+= -pg -fPIC
CXXFLAGS+= -g
#CXXFLAGS+= -fPIC -pthread
#CXXFLAGS+= -DUSE_SSE2
OPTIMALIZATION = -O0 -march=native -mtune=native  -I./include